spring:
  application:
    name: service-discovery
  cloud:
    compatibility-verifier:
      enabled: false # change when spring cloud release train supports spring boot 4.1.0

server:
  port: 8761

eureka:
  instance:
    hostname: localhost
    client:
      register-with-eureka: false
      fetchRegistry: false
      serviceUrl:
        defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/